### ISSUE TITLE
Selfhost without using GCP

### ISSUE THREAD

**Issue by chenghui-lee** [fishy/pandablog#1]
Hello, is it possible to self-host this application entirely without relying on GCP? The current `make local-run` command works for local development but not for production use (a lot of features are missing and the database resets automatically after some time).

Thanks.

**Comment by chenghui-lee** [comment]
Looks like this is possible.
Tried modifying the source code and is working as intended.
Closing this issue.

**Comment by fishy** [comment]
The database reset on local-run was actually a bug that gets fixed in e82164b4705ced9d1a5a083a43084c7803223b9a: https://github.com/fishy/pandablog/commit/e82164b4705ced9d1a5a083a43084c7803223b9a#diff-b8522ce70fb491c658ec2dafcba7fc81fa9e81b798f538f1652713c5498381bbR101
